-- MySQL Script generated by MySQL Workbench
-- Qua 23 Out 2019 13:36:42 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SE_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SE_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SE_DB` ;
USE `SE_DB` ;

-- -----------------------------------------------------
-- Table `SE_DB`.`Identificadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SE_DB`.`Identificadores` (
  `ID` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Altura` INT NOT NULL DEFAULT 10,
  `Largura` INT NOT NULL DEFAULT 10,
  `Comprimento` INT NOT NULL DEFAULT 10,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
